M48
; DRILL file KiCad 10.0.5 date 2026-07-26T05:11:30
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-07-26T05:11:30-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0197
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1063
%
G90
G05
T1
X4.3681Y-3.5493
T2
X5.274Y-5.5453
X5.5016Y-5.5453
T3
X4.372Y-2.812
X4.372Y-5.0719
X6.3957Y-2.812
X6.3957Y-5.0719
M30
