#pragma once

#include <cstddef>
#include <cstdint>

namespace doorbell {

enum class MqttFragmentResult : std::uint8_t {
    InProgress,
    Complete,
    Rejected,
};

struct MqttPayloadAssembly {
    std::size_t received{0};
    int expected_total{0};
    bool accepting{false};
};

void reset_mqtt_payload_assembly(MqttPayloadAssembly &assembly);

MqttFragmentResult append_mqtt_payload_fragment(
    MqttPayloadAssembly &assembly, char *payload, std::size_t payload_capacity,
    int current_offset, int total_length, const char *fragment,
    int fragment_length);

enum class GatewayCommandUrlKind : std::uint8_t {
    Audio,
    Acknowledgement,
};

/**
 * Accept only command URLs generated by the configured gateway.
 *
 * The comparison is deliberately stricter than a general URL parser: scheme,
 * authority, and port must exactly match GATEWAY_API_URL; query strings,
 * fragments, user-info, escapes, and path traversal are rejected; and the path
 * must have the exact shape emitted by SystemController.
 */
bool gateway_command_url_allowed(const char *candidate,
                                 const char *gateway_api_url,
                                 GatewayCommandUrlKind kind);

bool intercom_uuid_allowed(const char *candidate);

}  // namespace doorbell
